FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .
RUN if [ -f "go.mod" ]; then CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /infrapilot-agent ./cmd/agent; else cd agent && CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /infrapilot-agent ./cmd/agent; fi

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/
COPY --from=builder /infrapilot-agent .
CMD ["./infrapilot-agent"]
